FROM python:3.12-slim-bookworm

WORKDIR /app/fe

COPY fe_requirements.txt .

RUN pip install -r fe_requirements.txt

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "fe_app.py", "--server.port=8501", "--server.address=0.0.0.0"]