stages:
  data_collection:
    cmd: python backend/src/ml_pipeline/data_pipeline/data_collection.py
    deps:
      - backend/src/ml_pipeline/data_pipeline/data_collection.py
    outs:
      - backend/public/labelling 

  data_extraction:
    cmd: python backend/src/ml_pipeline/data_pipeline/data_extraction.py --params params.yaml
    deps:
      - backend/src/ml_pipeline/data_pipeline/data_extraction.py
      - backend/public/labelling
    params:
      - path
    outs:
      - backend/public/processed/annotations.json

  data_processing:
    cmd: python backend/src/ml_pipeline/data_pipeline/data_processing.py --params params.yaml
    deps: 
      - backend/src/ml_pipeline/data_pipeline/data_processing.py
      - backend/public/processed/annotations.json
    params:
      - train_valid
    outs:
      - backend/public/processed/train_ids.json
      - backend/public/processed/valid_ids.json

  main:
    cmd: python -m backend.src.ml_pipeline.main
    deps:
      - backend/src/ml_pipeline/main.py
      - backend/public/processed/train_ids.json
      - backend/public/processed/valid_ids.json
    outs: 
      - backend/src/ml_pipeline/model/model.pth