path:
  data_path: backend/public/data
  annotation_path: backend/public/processed/annotations.json

train_valid:
  test_size: 0.2
  random_state: 42
  train_output: backend/public/processed/train_ids.json # Output của bước split
  valid_output: backend/public/processed/valid_ids.json # Output của bước split

train:
  epochs: 50
  batch_size: 16