FROM python:3.12-slim-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends rclone git && \
    rm -rf /var/lib/apt/list/*

WORKDIR /app/ai

COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/src/ml_pipeline src/ml_pipline