FROM python:3.12-slim-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    rclone \
    git \
    libgl1-mesa-glx \
    libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*
    
WORKDIR /app/ai

COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/src/ml_pipeline src/ml_pipline