FROM python:3.12-slim-bookworm

RUN apt-get update && \ 
    apt-get install -y --no-install-recommends git openssh-client && \
    rm -rf /var/lib/apt/list/*

WORKDIR /app

COPY backend/dvc_requirements.txt .

RUN pip install --no-cache-dir -r dvc_requirements.txt